### ISSUE TITLE
Баги программы

### ISSUE THREAD

**Issue by stribog73** [DikBSD/freeLib#1]
В файле [https://disk.yandex.ru/d/heKJphbFclYDzA](https://disk.yandex.ru/d/heKJphbFclYDzA) две проблемные книги с описанием проблем.

**Comment by DikBSD** [comment]
Спасибо, посмотрю.

**Comment by DikBSD** [comment]
Баг, точнее, не доработка (этого раньше не было) про Nick Автора исправлен. Качайте новый релиз 7.3.0

По вопросу 2-й книги:  отображение обложки и аннотации буду править.

Напишите, пожалуйста, пошагово, как Вы удаляете эту книгу, откуда, и как пытаетесь ее восстановить. Желательно с скриншотами. Нужен еще скриншот Настроек вкладки Общие. У меня она восстанавливается.

**Comment by stribog73** [comment]
Выложу завтра или послезавтра со скриншотами. Сегодня не могу - немного приболел. Прошу извинить.

**Comment by DikBSD** [comment]
Ничего, я тоже приболел, "много" :)

**Comment by DikBSD** [comment]
Исправил, код залит в сюда репозиторий. Скоро выложу релизы.

**Comment by stribog73** [comment]
В жанрах CoolLib и ЛитВек произошли значительные изменения. Много жанров переименовано, а также, добавлено много новых жанров. Скачать список жанров от 11.05.21 можно отсюда: [https://disk.yandex.ru/d/HgHoShfcoYNwIA](https://disk.yandex.ru/d/HgHoShfcoYNwIA).
По всей видимости, это окончательный список и в ближайшие год-два меняться не будет.
