### ISSUE TITLE
WARNING: Failure to find: quazip/quazip/crypt.h

### ISSUE THREAD

**Issue by ssten** [DikBSD/freeLib#6]
При попытке сборки с встроенной версией библиотеки dev-libs/quazip наблюдаю сообщение:

> WARNING: Failure to find: quazip/quazip/crypt.h

Подозреваю: это жу-жу неспроста…

**Comment by DikBSD** [comment]
Буду править в понедельник. Залью код сюда. У меня нет Линукса, проверьте, пожалуйста, устранится ли этот баг.

**Comment by DikBSD** [comment]
В git репозитории папка quazip - это ссылка на репозитории quazip. Попробуйте склонировать код freeLib такой командой: **git clone freeLib --recurse-submodules**
Напишиие, пожалуйста, сработала ли после этого сборка Библиотекаря?
Я в readme.md позже укажу этот нюанс.

**Comment by ssten** [comment]
Не, *склонировалось* оно нормально без указания *дополнительных* опций.
Вопрос в том, что использовать склонированное **неправильно** (правильно — использовать библиотеку, установленную из **дистрибутивного** пакета).

**Comment by DikBSD** [comment]
Боюсь, что для этого придётся переписывать массу кода, поскольку в freelib задействован именно код quazip в .h, .c файлах. В будущем, если будет время, может попробую о вязать код библиотекарь от этого субмодуля, но не обещаю.

**Comment by ssten** [comment]
Для взаимопонимания и чтобы не делать лишней работы процитирую список файлов пакета *dev-libs/quazip-0.9.1*:

>$ qlist dev-libs/quazip
>/usr/lib64/pkgconfig/quazip.pc
>/usr/lib64/cmake/QuaZip5/QuaZip5Config.cmake
>/usr/lib64/libquazip5.so.1.0.0
>/usr/include/quazip5/JlCompress.h
>/usr/include/quazip5/ioapi.h
>/usr/include/quazip5/minizip_crypt.h
>/usr/include/quazip5/quaadler32.h
>/usr/include/quazip5/quachecksum32.h
>/usr/include/quazip5/quacrc32.h
>/usr/include/quazip5/quagzipfile.h
>/usr/include/quazip5/quaziodevice.h
>/usr/include/quazip5/quazip.h
>/usr/include/quazip5/quazip_global.h
>/usr/include/quazip5/quazipdir.h
>/usr/include/quazip5/quazipfile.h
>/usr/include/quazip5/quazipfileinfo.h
>/usr/include/quazip5/quazipnewinfo.h
>/usr/include/quazip5/unzip.h
>/usr/include/quazip5/zip.h
>/usr/share/doc/quazip-0.9.1/README.md.bz2
>/usr/lib64/libquazip5.so.1
>/usr/lib64/libquazip5.so
>/usr/lib64/libquazip.so

**Comment by DikBSD** [comment]
У меня все заработало при услановке quazip библиотек следующим образом:
`sudo apt install libquazip*`

Скоро выложу обновленный, исправленный код...
