### ISSUE TITLE
Build failure (with gcc-10 compiler)

### ISSUE THREAD

**Issue by ssten** [DikBSD/freeLib#7]
For now I use sys-devel/gcc-10.2.0-r5 compiler.

Build (of latest git version) fails with the following message:

>In file included from library.cpp:2:
>library.h: In constructor ‘Group::Group(const QString&, uint, bool, const QString&)’:
>library.h:91:10: warning: ‘Group::Blocked_’ will be initialized after [-Wreorder]
>   91 |     bool Blocked_;
>      |          ^~~~~~~~
>library.h:89:13: warning:   ‘QString Group::BlockedName_’ [-Wreorder]
>   89 |     QString BlockedName_;
>      |             ^~~~~~~~~~~~
>library.h:96:5: warning:   when initialized here [-Wreorder]
>   96 |     Group(const QString& Name, uint id, bool blocked, const QString& blockedName = "") :
>      |     ^~~~~
>library.h: In member function ‘QString Group::getId() const’:
>library.h:103:36: error: invalid conversion from ‘uint’ {aka ‘unsigned int’} to ‘const char*’ [-fpermissive]
>  103 |     QString getId() const { return Id_; };
>      |                                    ^~~
>      |                                    |
>      |                                    uint {aka unsigned int}
>In file included from /usr/include/qt5/QtCore/qobject.h:47,
>                 from /usr/include/qt5/QtCore/qsettings.h:43,
>                 from /usr/include/qt5/QtCore/QSettings:1,
>                 from common.h:4,
>                 from library.cpp:1:
>/usr/include/qt5/QtCore/qstring.h:835:51: note:   initializing argument 1 of ‘QString::QString(const char*)’
>  835 |     inline QT_ASCII_CAST_WARN QString(const char *ch)
>      |                                       ~~~~~~~~~~~~^~
>make[1]: *** [Makefile:1049: library.o] Error 1
>make[1]: *** Waiting for unfinished jobs....
>In file included from opds_server.h:10,
>                 from mainwindow.h:18,
>                 from main.cpp:16:
>library.h: In constructor ‘Group::Group(const QString&, uint, bool, const QString&)’:
>library.h:91:10: warning: ‘Group::Blocked_’ will be initialized after [-Wreorder]
>   91 |     bool Blocked_;
>      |          ^~~~~~~~
>library.h:89:13: warning:   ‘QString Group::BlockedName_’ [-Wreorder]
>   89 |     QString BlockedName_;
>      |             ^~~~~~~~~~~~
>library.h:96:5: warning:   when initialized here [-Wreorder]
>   96 |     Group(const QString& Name, uint id, bool blocked, const QString& blockedName = "") :
>      |     ^~~~~
>library.h: In member function ‘QString Group::getId() const’:
>library.h:103:36: error: invalid conversion from ‘uint’ {aka ‘unsigned int’} to ‘const char*’ [-fpermissive]
>  103 |     QString getId() const { return Id_; };
>      |                                    ^~~
>      |                                    |
>      |                                    uint {aka unsigned int}
>In file included from /usr/include/qt5/QtCore/qcoreapplication.h:44,
>                 from /usr/include/qt5/QtWidgets/qapplication.h:44,
>                 from /usr/include/qt5/QtWidgets/QApplication:1,
>                 from main.cpp:1:
>/usr/include/qt5/QtCore/qstring.h:835:51: note:   initializing argument 1 of ‘QString::QString(const char*)’
>  835 |     inline QT_ASCII_CAST_WARN QString(const char *ch)
>      |                                       ~~~~~~~~~~~~^~
>

Linux 5.4 amd64.

**Comment by DikBSD** [comment]
Исправлю в ближайшее время, спасибо за сообщение. Удивлён безмерно, что мой косяк компилятор на Windows в VS 2019 обработал корректно (неявно преобразовал QString в uint), тогда как gcc на Линуксе не стал этого делать, что правильно.

**Comment by ssten** [comment]
Ну, с *gcc* тоже бывают нюансы…

> // Про новую версию компилятора Си gcc-8
> 
>Чё ты мне стандартом в морду тычешь? У прадедов работало, у дедов работало, у меня всё работало, пока какой-то моржовый хер стандарт не почитал и не сломал всё.

[#18263](http://www.ibash.org.ru/quote.php?id=18263)

**Comment by DikBSD** [comment]
Исправлено.
