### ISSUE TITLE
missed LICENSE file?

### ISSUE THREAD

**Issue by ssten** [DikBSD/freeLib#9]
Не нашёл на привычном месте файлак с указанием на условия лицензирования.
Не там искал или авторы этим вопросом не озаботились (и читаем «as-is»)?

**Comment by DikBSD** [comment]
Вы правы надо будет положить файл лицензии в корень папки с исходниками. GPL3. Думаю, эта лицензия будет оптимальной. Как Вы считаете? или - лучше другую?

**Comment by DikBSD** [comment]
Добавлен файл лицензии.
